gps_goto_node:
  ros__parameters:
    waypoint_csv: "/home/hyeonseo/hlfma2025/src/decision_making_pkg/config/waypoints_center.csv"
    arrive_dist_m: 2.0
    stop_wp_indices: "[]"
    pause_wp_indices: "[17]"
    pause_seconds: 4.0
    reverse_ranges: "" #, 396-407"
    speed_forward_pwm: 180
    speed_reverse_pwm: -80
    sub_lidar_topic: "/lidar_processed"
    lidar_activation_ranges: "327-355" 
    speed_lidar_zone_pwm: 200
    speed_prepare_zone_pwm: 100
    traffic_light_left_confidence_count: 100

    # -- 신호등 설정 --
    sub_traffic_light_topic: "yolov8_traffic_light_info"
    traffic_light_green_go_ranges: "88-90, 167-169" # Green 신호에 출발하는 구간
    traffic_light_left_go_ranges: "273-275"       # Left 신호에 출발하는 구간


    # -- T자 주차 미션 설정 --
    t_parking_prepare_ranges: "185-189"
    t_parking_mission_ranges: "190-210"  # T자 주차 미션을 시도할 메인 경로의 웨이포인트 구간
    t_parking_left_csv: "/home/hyeonseo/hlfma2025/src/decision_making_pkg/config/tleft.csv" # yellow 우선 감지 시 주행 경로
    t_parking_right_csv: "/home/hyeonseo/hlfma2025/src/decision_making_pkg/config/tright.csv"  # cone 우선 감지 시 주행 경로

    # -- 평행 주차 미션 설정 --
    parallel_parking_prepare_ranges: "390-390"
    parallel_parking_mission_ranges: "391-412" # 평행 주차 미션을 시도할 메인 경로의 웨이포인트 구간
    p_parking_left_csv: "/home/hyeonseo/hlfma2025/src/decision_making_pkg/config/pleft.csv" # cone 우선 감지 시 주행 경로
    p_parking_right_csv: "/home/hyeonseo/hlfma2025/src/decision_making_pkg/config/pright.csv" # yellow 우선 감지 시 주행 경로

    # -- 객체 탐지 노드 토픽 설정 --
    sub_object_left_topic: "/object/left/detection_order"
    sub_object_right_topic: "/object/right/detection_order"